### ISSUE TITLE
Is it possible to alter the icon of UWP app?

### ISSUE THREAD

**Issue by Weilet** [hv0905/SaberColorfulStartmenu#10]
I use some uwp apps and I can't find them in the list.
Is it possible to alter the icon of the UWP app?

**Comment by hv0905** [comment]
Unfortunately, It's impossible to change the UWP app's tile because the icon setting is bundled in the app and controlled by the app develop.


If you are an UWP app's develop, you can checkout [this page](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/creating-tiles) to change your own UWP app's tile at development. But if you are just a user, It's impossible for you to change it.


By the way, some apps have a setting to allow users to customize the tile, such as `网易云音乐UWP`.
![image](https://user-images.githubusercontent.com/29349119/75085298-d06a3a00-5562-11ea-8565-7d4be6dfa81b.png)
